DEBUG_MODE = True

# Hardware config
GPIO_CHIP_PATH = "/dev/gpiochip0"
GPIO_POWER_STATUS_PIN = 23
GPIO_IR_INPUT_PIN = 27

PATH_SERIAL_DEBUG = '/dev/serial0'

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

MOTION_WIDTH = 320
MOTION_HEIGHT = 240

MOTION_THRESHOLD = 200
MOTION_COOLDOWN_SEC = 5
