import serial

# Logging
LOG_LEVEL = "INFO"        # DEBUG, INFO, WARNING, ERROR
LOG_TO_CONSOLE = True
LOG_TO_FILE = True
LOG_FILE_PATH = "../log/smartmirrord.log"

# Fine-grained control
UART_DEBUG = False

# Hardware config
GPIO_CHIP_PATH = "/dev/gpiochip0"
GPIO_POWER_STATUS_PIN = 23
GPIO_IR_INPUT_PIN = 27

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

MOTION_WIDTH = 320
MOTION_HEIGHT = 240

MOTION_THRESHOLD = 150
MOTION_COOLDOWN_SEC = 4

UART_PORT = '/dev/serial0'
UART_BAUDRATE = 115200
UART_PARITY = serial.PARITY_NONE
UART_STOPBITS = serial.STOPBITS_ONE
UART_BYTESIZE = serial.EIGHTBITS
UART_TIMEOUT = .1
UART_READ_CHUNK_SIZE = 1024
UART_WRITE_EOL = '\n'

